apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-pgbouncer-auth
  labels:
    application: pgbouncer
    cluster-name: {{ .Values.clusterName }}
type: Opaque
data:
  # 這裡使用 Patroni 的 Superuser 密碼作為 pgbouncer 的認證密碼
  # 實際部署中，建議為 pgbouncer 創建一個專用密碼
  pgbouncer-auth: {{ .Values.secret.superuserPassword }} 
