apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}
  labels:
    application: patroni
    cluster-name: {{ .Values.clusterName }}
type: Opaque
data:
  superuser-password: {{ .Values.secret.superuserPassword }}
  replication-password: {{ .Values.secret.replicationPassword }}
